- ros_topic_name: "/velodyne_points/points"
  gz_topic_name: "/velodyne_points/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA